language: python
branch:
  only:
  - master
  - gh-pages
script: print "- indices[i], arr[indices[i]]" > _sidebar.md
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
